version: '3.9'

services:
  postgres:
    container_name: potgres
    image: postgres:13-alpine
    volumes:
      - ec_postgres_data:/var/lib/postgresql/data/
    environment: 
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=postgres
    restart: on-failure
  redis:
    container_name: redis
    image: redis
    ports:
     - 6379:6379
    restart: on-failure
    volumes:
      - ec_redis_data:/data
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: web
    volumes:
      - .:/usr/src/ecommerce_app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
      - redis
    restart: on-failure
  celery:
    build: .
    command: celery -A config worker -l info
    container_name: celery_worker
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - postgres
      - web
    restart: on-failure
volumes:
  ec_postgres_data:
  ec_redis_data:
