version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - ec_postgres_data:/var/lib/postgresql/data/
    env_file: 
      - ./.env.prod.db
    restart: on-failure
  redis:
    container_name: redis
    image: redis
    ports:
     - 6379:6379
    restart: on-failure
    volumes:
      - ec_redis_data:/data
  web:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    container_name: web
    volumes:
      - .:/usr/src/ecommerce_app/
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
      - redis
    restart: on-failure
  celery:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    command: celery -A config worker -l info
    container_name: celery_worker
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - postgres
      - web
    restart: on-failure
  nginx:
    container_name: nginx
    build: ./nginx
    ports: 
      - 80:80
    volumes: 
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on: 
      - web
volumes:
  ec_postgres_data:
  ec_redis_data:
  static_volume:
  media_volume:
